### ISSUE TITLE
Erroneous variable names

### ISSUE THREAD

**Issue by jesperelements** [mrackwitz/xcres#18]
When using xcres in a project, it generates a file with some erroneous variable names

Example:

extern const struct R {
    struct Images {
        /// Icon-100.png
        __unsafe_unretained NSString *100;

**Comment by nikitaUnii** [comment]
It strips Icon for me even when it's not redundant: `R.ImagesAssets.World` instead of `R.ImagesAssets.IconWorld` why is that so?

**Comment by mrackwitz** [comment]
"Icon" and "Image" are defined as general filter words. Unfortunaley there is no other way than [modifying the source to disable that] (https://github.com/mrackwitz/xcres/blob/master/lib/xcres/analyzer/resources_analyzer/base_resources_analyzer.rb#L12). PR welcome!
