### ISSUE TITLE
Gem conflict with Cocoapods

### ISSUE THREAD

**Issue by samjarman** [mrackwitz/xcres#31]
Hey... Unsure if this is the right place for this (forgive me Marius if that's the case) but I'm getting this gem conflict with Active Support and Xcodeproj... wondering if anyone else solved it?

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    cocoapods (= 1.0.0) was resolved to 1.0.0, which depends on
      activesupport (>= 4.0.2)

    cocoapods (= 1.0.0) was resolved to 1.0.0, which depends on
      activesupport (>= 4.0.2)

    cocoapods (= 1.0.0) was resolved to 1.0.0, which depends on
      xcodeproj (< 2.0, >= 1.0.0) was resolved to 1.0.0, which depends on
        activesupport (>= 3)

    cocoapods (= 1.0.0) was resolved to 1.0.0, which depends on
      xcodeproj (< 2.0, >= 1.0.0) was resolved to 1.0.0, which depends on
        activesupport (>= 3)

    xcres (= 0.6.0) was resolved to 0.6.0, which depends on
      activesupport (< 4, >= 3.2.15)
```

**Comment by pietbrauer** [comment]
@samjarman Seems to be valid. From [`Gemfile`](https://github.com/mrackwitz/xcres/blob/master/xcres.gemspec#L39):

```ruby
spec.add_runtime_dependency 'activesupport', '>= 3.2.15', '< 4'
```

Do you mind sending a PullRequest that updates the active support dependency to match CocoaPods?

**Comment by samjarman** [comment]
Hey @pietbrauer, I made a trivial PR to see if it worked. Looks like Travis is having some issues. I'm also unsure why that upper version limit was put there in the first place - I suspect there's a good/API related reason?
