### ISSUE TITLE
camel case not generated when using . as separator

### ISSUE THREAD

**Issue by lagubull** [mrackwitz/xcres#33]
Camel case is created fine when using "my-variable" but when using "my.variable" it just deletes the . which makes it all flat and impossible to read. Can . be added as a recognised separator?

**Comment by pietbrauer** [comment]
Do you mind opening a PullRequest for that? What I could see the code should be somewhere in [xcres/resources_builder.rb](https://github.com/mrackwitz/xcres/blob/master/lib/xcres/builder/resources_builder.rb#L114-L145).

**Comment by lagubull** [comment]
I have just done so. Not very sure if it is the best place for the modification but it does work.

**Comment by pietbrauer** [comment]
Close via #34
