### ISSUE TITLE
Compile error when generated string begins with number

### ISSUE THREAD

**Issue by MKGitHub** [mrackwitz/xcres#9]
I'm using ibtool to generate .strings files which are extracted from my .xib/.storyboard file. Now ibtool will create strings like this:

"8ie-xW-0ye.text" = "Hello World";

Then the issue with xcres is that it creates the below variable with the same name which starts with the number 8, which in turn is not a valid variable or constant name – which causes a compile error.

struct Strings {
        __unsafe_unretained NSString *8ieXW0yetext;

**Comment by josejulio** [comment]
Wouldn't it be possible to add a underscore (_) to strings that begin with a number? e.g. On the code there is some animations that are just numbered: 01.png, 02.png, etc
Turn this:
``c
        /// 01.png
        __unsafe_unretained NSString *01;
        /// 02.png
        __unsafe_unretained NSString *02;
``
To:
``c
        /// 01.png
        __unsafe_unretained NSString *_01;
        /// 02.png
        __unsafe_unretained NSString *_02;
``
